config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#home'
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  # resources :bookmarks, only: ["delete"]
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def home; end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container form-white">
  <%= simple_form_for [@list, @bookmark] do |b| %>
    <%= b.input :comment %>
    <%= b.association :movie %>
    <%= b.submit %>
  <% end %>
  <br>
  <%= link_to "Cancel", list_path(@list)  %>
</div>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #1a1a1a;">
    <%= render "components/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/home.html.erb
<%= link_to "View Lists", lists_path  %>

app/views/lists/index.html.erb
<div class="container">

  <ul class="card-list">
    <% @lists.each do |l| %>
      <% if l.photo.attached? %>
        <%= link_to list_path(l) do %>
          <li class="card card-glow" id="list-card">
            <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path l.photo.key, height: 300, width: 400, crop: :fill %>)">
              <%= link_to l.name, list_path(l), class: "card-link" %>
              <%= link_to "Remove", list_path(l), method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </li>
        <% end %>
      <% else %>
        <%= link_to list_path(l) do %>
          <li class="card card-glow" id="list-card">
            <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80')">
              <%= link_to l.name, list_path(l), class: "card-link" %>
              <%= link_to "Remove", list_path(l), method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container form-white">
    <%= simple_form_for(@list) do |l| %>
      <%= l.input :name %>
      <%= l.input :photo, as: :file %>
      <%= l.submit %>
    <% end %>
    <br>
    <%= link_to "Cancel", lists_path  %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="show-title">
    <h1><%= @list.name %></h1>
    <span><%= link_to "Add a movie to the list", new_list_bookmark_path(@list) %></span>
  </div>
  <ul>
    <% @bookmarks.each do |b| %>
      <% if b.list == @list %>
        <li class="card card-glow">
          <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= b.movie.poster_url %>)">
            <%= link_to b.movie.title, bookmark_path(b), class: "card-link" %> -
            <%= link_to "Remove", bookmark_path(b), method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>